services:
  # Backend API Service
  - type: web
    name: pathfinder-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: API_PREFIX
        value: api/v1
      - key: DATABASE_SSL
        value: true
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: RATE_LIMIT_TTL
        value: 60
      - key: RATE_LIMIT_MAX
        value: 100
      - key: JWT_EXPIRATION
        value: 7d
      - key: JWT_REFRESH_EXPIRATION
        value: 30d
      # Secrets - Configure no painel do Render
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

databases:
  # PostgreSQL Database
  - name: pathfinder-db
    databaseName: pathfinder_production
    user: pathfinder
    plan: starter
    region: oregon
    ipAllowList: []
