import { AchievementRarity } from '../../modules/gamification/entities/achievement-catalog.entity';

export const ACHIEVEMENTS_SEED = [
  // ============ STREAK ACHIEVEMENTS ============
  {
    achievementId: 'streak_7',
    title: 'Semana Consistente',
    description: 'Mantenha um streak de 7 dias consecutivos',
    icon: '🔥',
    xpReward: 100,
    rarity: AchievementRarity.COMMON,
    mbtiTypes: null, // Universal
    requirementType: 'streak',
    requirementValue: 7,
  },
  {
    achievementId: 'streak_30',
    title: 'Mestre da Disciplina',
    description: 'Mantenha um streak de 30 dias consecutivos',
    icon: '⚡',
    xpReward: 500,
    rarity: AchievementRarity.RARE,
    mbtiTypes: null,
    requirementType: 'streak',
    requirementValue: 30,
  },
  {
    achievementId: 'streak_100',
    title: 'Lenda da Consistência',
    description: 'Mantenha um streak de 100 dias consecutivos',
    icon: '👑',
    xpReward: 2000,
    rarity: AchievementRarity.LEGENDARY,
    mbtiTypes: null,
    requirementType: 'streak',
    requirementValue: 100,
  },

  // ============ JOURNAL ACHIEVEMENTS ============
  {
    achievementId: 'journal_10',
    title: 'Diário Iniciante',
    description: 'Escreva 10 entradas no seu diário',
    icon: '📝',
    xpReward: 150,
    rarity: AchievementRarity.COMMON,
    mbtiTypes: null,
    requirementType: 'journal_count',
    requirementValue: 10,
  },
  {
    achievementId: 'journal_50',
    title: 'Escritor Reflexivo',
    description: 'Escreva 50 entradas no seu diário',
    icon: '📖',
    xpReward: 600,
    rarity: AchievementRarity.RARE,
    mbtiTypes: null,
    requirementType: 'journal_count',
    requirementValue: 50,
  },
  {
    achievementId: 'journal_100',
    title: 'Mestre do Autoconhecimento',
    description: 'Escreva 100 entradas no seu diário',
    icon: '📚',
    xpReward: 1500,
    rarity: AchievementRarity.EPIC,
    mbtiTypes: null,
    requirementType: 'journal_count',
    requirementValue: 100,
  },

  // ============ TEST ACHIEVEMENTS ============
  {
    achievementId: 'test_first',
    title: 'Primeiro Passo',
    description: 'Complete seu primeiro teste de personalidade',
    icon: '🎯',
    xpReward: 50,
    rarity: AchievementRarity.COMMON,
    mbtiTypes: null,
    requirementType: 'tests_completed',
    requirementValue: 1,
  },
  {
    achievementId: 'test_all_mbti',
    title: 'Explorador de Tipos',
    description: 'Complete o teste MBTI',
    icon: '🧩',
    xpReward: 200,
    rarity: AchievementRarity.RARE,
    mbtiTypes: null,
    requirementType: 'tests_completed',
    requirementValue: 3,
  },

  // ============ CHALLENGE ACHIEVEMENTS ============
  {
    achievementId: 'challenge_1',
    title: 'Desafiante',
    description: 'Complete seu primeiro desafio semanal',
    icon: '💪',
    xpReward: 200,
    rarity: AchievementRarity.COMMON,
    mbtiTypes: null,
    requirementType: 'challenges_completed',
    requirementValue: 1,
  },
  {
    achievementId: 'challenge_5',
    title: 'Guerreiro do Crescimento',
    description: 'Complete 5 desafios semanais',
    icon: '⚔️',
    xpReward: 800,
    rarity: AchievementRarity.RARE,
    mbtiTypes: null,
    requirementType: 'challenges_completed',
    requirementValue: 5,
  },
  {
    achievementId: 'challenge_10',
    title: 'Campeão da Transformação',
    description: 'Complete 10 desafios semanais',
    icon: '🏆',
    xpReward: 2000,
    rarity: AchievementRarity.EPIC,
    mbtiTypes: null,
    requirementType: 'challenges_completed',
    requirementValue: 10,
  },

  // ============ CONTENT ACHIEVEMENTS ============
  {
    achievementId: 'content_10',
    title: 'Curioso',
    description: 'Consuma 10 conteúdos educacionais',
    icon: '📰',
    xpReward: 100,
    rarity: AchievementRarity.COMMON,
    mbtiTypes: null,
    requirementType: 'content_consumed',
    requirementValue: 10,
  },
  {
    achievementId: 'content_50',
    title: 'Estudioso',
    description: 'Consuma 50 conteúdos educacionais',
    icon: '🎓',
    xpReward: 500,
    rarity: AchievementRarity.RARE,
    mbtiTypes: null,
    requirementType: 'content_consumed',
    requirementValue: 50,
  },
  {
    achievementId: 'content_100',
    title: 'Sábio do Pathfinder',
    description: 'Consuma 100 conteúdos educacionais',
    icon: '🧠',
    xpReward: 1200,
    rarity: AchievementRarity.EPIC,
    mbtiTypes: null,
    requirementType: 'content_consumed',
    requirementValue: 100,
  },

  // ============ XP MILESTONES ============
  {
    achievementId: 'xp_1000',
    title: 'Explorador',
    description: 'Alcance 1000 XP total',
    icon: '🌟',
    xpReward: 200,
    rarity: AchievementRarity.COMMON,
    mbtiTypes: null,
    requirementType: 'total_xp',
    requirementValue: 1000,
  },
  {
    achievementId: 'xp_5000',
    title: 'Veterano',
    description: 'Alcance 5000 XP total',
    icon: '✨',
    xpReward: 500,
    rarity: AchievementRarity.RARE,
    mbtiTypes: null,
    requirementType: 'total_xp',
    requirementValue: 5000,
  },
  {
    achievementId: 'xp_10000',
    title: 'Mestre Pathfinder',
    description: 'Alcance 10000 XP total',
    icon: '💎',
    xpReward: 1000,
    rarity: AchievementRarity.EPIC,
    mbtiTypes: null,
    requirementType: 'total_xp',
    requirementValue: 10000,
  },

  // ============ SPECIAL MBTI ACHIEVEMENTS ============
  {
    achievementId: 'intj_strategic',
    title: 'Mestre Estrategista',
    description: 'Complete 5 desafios como INTJ',
    icon: '🎭',
    xpReward: 300,
    rarity: AchievementRarity.RARE,
    mbtiTypes: ['INTJ'],
    requirementType: 'challenges_completed',
    requirementValue: 5,
  },
  {
    achievementId: 'enfp_creative',
    title: 'Alma Criativa',
    description: 'Consuma 30 conteúdos como ENFP',
    icon: '🎨',
    xpReward: 300,
    rarity: AchievementRarity.RARE,
    mbtiTypes: ['ENFP'],
    requirementType: 'content_consumed',
    requirementValue: 30,
  },
  {
    achievementId: 'istj_organized',
    title: 'Guardião da Ordem',
    description: 'Mantenha 60 dias de streak como ISTJ',
    icon: '📋',
    xpReward: 400,
    rarity: AchievementRarity.EPIC,
    mbtiTypes: ['ISTJ'],
    requirementType: 'streak',
    requirementValue: 60,
  },
  {
    achievementId: 'infp_authentic',
    title: 'Coração Autêntico',
    description: 'Escreva 50 entradas no diário como INFP',
    icon: '💜',
    xpReward: 400,
    rarity: AchievementRarity.EPIC,
    mbtiTypes: ['INFP'],
    requirementType: 'journal_count',
    requirementValue: 50,
  },

  // ============ PROFILE COMPLETION ============
  {
    achievementId: 'profile_complete',
    title: 'Perfil Completo',
    description: 'Complete todas as informações do seu perfil',
    icon: '👤',
    xpReward: 100,
    rarity: AchievementRarity.COMMON,
    mbtiTypes: null,
    requirementType: 'profile_completed',
    requirementValue: 1,
  },

  // ============ EARLY ADOPTER ============
  {
    achievementId: 'early_adopter',
    title: 'Pioneiro',
    description: 'Seja um dos primeiros usuários do Pathfinder',
    icon: '🚀',
    xpReward: 500,
    rarity: AchievementRarity.LEGENDARY,
    mbtiTypes: null,
    requirementType: 'account_age_days',
    requirementValue: 1,
  },
];
