import { ContentType, Difficulty } from '../../modules/content-library/entities/content-library.entity';

export const CONTENT_LIBRARY_SEED = [
  // ========================================
  // ARTIGOS - LIDERANÇA
  // ========================================
  {
    contentId: 'article_leadership_estj',
    title: 'Liderança Eficiente: O Poder da Organização',
    type: ContentType.ARTICLE,
    url: 'https://www.forbes.com/leadership-organization',
    description: 'Como ESTJs podem usar suas habilidades naturais de organização para liderar equipes de alta performance.',
    durationMinutes: 8,
    xpReward: 5,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ'],
    categories: ['leadership', 'productivity'],
    difficulty: Difficulty.INTERMEDIATE,
  },
  {
    contentId: 'article_servant_leadership',
    title: 'Liderança Servidora: Liderar Servindo',
    type: ContentType.ARTICLE,
    url: 'https://hbr.org/servant-leadership',
    description: 'Para INFJs e ENFJs: como liderar através do empoderamento e serviço aos outros.',
    durationMinutes: 10,
    xpReward: 5,
    mbtiTypes: ['INFJ', 'ENFJ', 'ISFJ', 'ESFJ'],
    categories: ['leadership', 'empathy'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'article_visionary_leadership',
    title: 'Liderança Visionária: Inspirando Mudança',
    type: ContentType.ARTICLE,
    url: 'https://www.strategy-business.com/visionary-leadership',
    description: 'INTJs e ENTJs: como transformar visões ousadas em realidade.',
    durationMinutes: 12,
    xpReward: 5,
    mbtiTypes: ['INTJ', 'ENTJ', 'INFJ', 'ENFJ'],
    categories: ['leadership', 'strategy'],
    difficulty: Difficulty.ADVANCED,
  },

  // ========================================
  // ARTIGOS - RELACIONAMENTOS
  // ========================================
  {
    contentId: 'article_communication_introverts',
    title: 'Comunicação Eficaz para Introvertidos',
    type: ContentType.ARTICLE,
    url: 'https://www.psychologytoday.com/introverts-communication',
    description: 'Estratégias de comunicação que respeitam a natureza introvertida.',
    durationMinutes: 7,
    xpReward: 5,
    mbtiTypes: ['INTJ', 'INFJ', 'ISTJ', 'ISFJ', 'INTP', 'INFP', 'ISTP', 'ISFP'],
    categories: ['relationships', 'communication'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'article_conflict_resolution',
    title: 'Resolução de Conflitos: Guia Prático',
    type: ContentType.ARTICLE,
    url: 'https://www.mindtools.com/conflict-resolution',
    description: 'Técnicas para navegar conflitos de forma saudável, especialmente para tipos T.',
    durationMinutes: 9,
    xpReward: 5,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESTP', 'ENTP', 'ISTP', 'INTP'],
    categories: ['relationships', 'conflict'],
    difficulty: Difficulty.INTERMEDIATE,
  },
  {
    contentId: 'article_emotional_intelligence',
    title: 'Desenvolvendo Inteligência Emocional',
    type: ContentType.ARTICLE,
    url: 'https://hbr.org/emotional-intelligence',
    description: 'Para tipos T: como desenvolver habilidades emocionais sem perder a racionalidade.',
    durationMinutes: 11,
    xpReward: 5,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESTP', 'ENTP', 'ISTP', 'INTP'],
    categories: ['relationships', 'emotions', 'growth'],
    difficulty: Difficulty.ADVANCED,
  },

  // ========================================
  // VÍDEOS - PRODUTIVIDADE
  // ========================================
  {
    contentId: 'video_time_management',
    title: 'Gestão de Tempo para Perfeccionistas',
    type: ContentType.VIDEO,
    url: 'https://youtube.com/watch?v=time-management',
    description: 'Como tipos J podem otimizar ainda mais sua gestão de tempo.',
    durationMinutes: 15,
    xpReward: 10,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESFJ', 'ENFJ', 'ISFJ', 'INFJ'],
    categories: ['productivity', 'time-management'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'video_creative_productivity',
    title: 'Produtividade Criativa para Tipos P',
    type: ContentType.VIDEO,
    url: 'https://youtube.com/watch?v=creative-productivity',
    description: 'Sistemas flexíveis de produtividade que respeitam a espontaneidade.',
    durationMinutes: 18,
    xpReward: 10,
    mbtiTypes: ['ESTP', 'ENTP', 'ISTP', 'INTP', 'ESFP', 'ENFP', 'ISFP', 'INFP'],
    categories: ['productivity', 'creativity'],
    difficulty: Difficulty.INTERMEDIATE,
  },
  {
    contentId: 'video_deep_work',
    title: 'Deep Work: Foco Profundo',
    type: ContentType.VIDEO,
    url: 'https://youtube.com/watch?v=deep-work',
    description: 'Para INTJs e INTPs: como maximizar períodos de trabalho profundo.',
    durationMinutes: 20,
    xpReward: 10,
    mbtiTypes: ['INTJ', 'INTP', 'ISTJ', 'ISTP'],
    categories: ['productivity', 'focus'],
    difficulty: Difficulty.ADVANCED,
  },

  // ========================================
  // LIVROS - CRESCIMENTO PESSOAL
  // ========================================
  {
    contentId: 'book_atomic_habits',
    title: 'Hábitos Atômicos - James Clear',
    type: ContentType.BOOK,
    url: 'https://www.amazon.com/Atomic-Habits-James-Clear',
    description: 'Construa hábitos pequenos que geram resultados extraordinários.',
    durationMinutes: 300,
    xpReward: 25,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESFJ', 'ENFJ', 'ISFJ', 'INFJ'],
    categories: ['habits', 'growth', 'productivity'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'book_thinking_fast_slow',
    title: 'Rápido e Devagar - Daniel Kahneman',
    type: ContentType.BOOK,
    url: 'https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman',
    description: 'Entenda os dois sistemas de pensamento. Essencial para INTJs e INTPs.',
    durationMinutes: 420,
    xpReward: 30,
    mbtiTypes: ['INTJ', 'INTP', 'ENTJ', 'ENTP'],
    categories: ['psychology', 'decision-making', 'cognition'],
    difficulty: Difficulty.ADVANCED,
  },
  {
    contentId: 'book_daring_greatly',
    title: 'A Coragem de Ser Imperfeito - Brené Brown',
    type: ContentType.BOOK,
    url: 'https://www.amazon.com/Daring-Greatly-Brene-Brown',
    description: 'Vulnerabilidade como força. Transformador para tipos F.',
    durationMinutes: 360,
    xpReward: 25,
    mbtiTypes: ['INFJ', 'INFP', 'ENFJ', 'ENFP', 'ISFJ', 'ISFP', 'ESFJ', 'ESFP'],
    categories: ['vulnerability', 'courage', 'authenticity'],
    difficulty: Difficulty.INTERMEDIATE,
  },

  // ========================================
  // EXERCÍCIOS - AUTOCONHECIMENTO
  // ========================================
  {
    contentId: 'exercise_values_clarification',
    title: 'Exercício: Clarificação de Valores',
    type: ContentType.EXERCISE,
    url: 'https://pathfinder.com/exercises/values',
    description: 'Identifique seus 5 valores fundamentais através de perguntas profundas.',
    durationMinutes: 30,
    xpReward: 15,
    mbtiTypes: ['INFJ', 'INFP', 'ENFJ', 'ENFP', 'INTJ', 'INTP', 'ENTJ', 'ENTP'],
    categories: ['values', 'reflection', 'purpose'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'exercise_cognitive_functions',
    title: 'Exercício: Explorando Funções Cognitivas',
    type: ContentType.EXERCISE,
    url: 'https://pathfinder.com/exercises/cognitive-functions',
    description: 'Entenda profundamente suas funções cognitivas MBTI.',
    durationMinutes: 45,
    xpReward: 20,
    mbtiTypes: ['INTJ', 'INFJ', 'ENTJ', 'ENFJ', 'INTP', 'INFP', 'ENTP', 'ENFP'],
    categories: ['mbti', 'cognition', 'self-awareness'],
    difficulty: Difficulty.ADVANCED,
  },
  {
    contentId: 'exercise_shadow_work',
    title: 'Exercício: Trabalho com a Sombra',
    type: ContentType.EXERCISE,
    url: 'https://pathfinder.com/exercises/shadow-work',
    description: 'Explore aspectos ocultos da sua personalidade (Jungian Shadow).',
    durationMinutes: 40,
    xpReward: 20,
    mbtiTypes: ['INFJ', 'INFP', 'INTJ', 'INTP', 'ENFJ', 'ENFP', 'ENTJ', 'ENTP'],
    categories: ['jung', 'shadow', 'depth-psychology'],
    difficulty: Difficulty.ADVANCED,
  },

  // ========================================
  // PODCASTS - DESENVOLVIMENTO
  // ========================================
  {
    contentId: 'podcast_personality_hacker',
    title: 'Personality Hacker Podcast - Ep. 001',
    type: ContentType.PODCAST,
    url: 'https://personalityhacker.com/podcast',
    description: 'Explorando tipos de personalidade através de funções cognitivas.',
    durationMinutes: 50,
    xpReward: 15,
    mbtiTypes: ['INTJ', 'INFJ', 'ENTJ', 'ENFJ', 'INTP', 'INFP', 'ENTP', 'ENFP'],
    categories: ['mbti', 'cognitive-functions', 'depth'],
    difficulty: Difficulty.INTERMEDIATE,
  },
  {
    contentId: 'podcast_hidden_brain',
    title: 'Hidden Brain - Compreendendo Vieses',
    type: ContentType.PODCAST,
    url: 'https://hiddenbrain.org',
    description: 'Ciência do comportamento humano e vieses cognitivos.',
    durationMinutes: 45,
    xpReward: 15,
    mbtiTypes: ['INTJ', 'INTP', 'ENTJ', 'ENTP', 'INFJ', 'INFP', 'ENFJ', 'ENFP'],
    categories: ['psychology', 'science', 'bias'],
    difficulty: Difficulty.BEGINNER,
  },

  // ========================================
  // CONTEÚDO ESPECÍFICO POR TIPO
  // ========================================
  {
    contentId: 'article_intj_relationships',
    title: 'INTJs em Relacionamentos: Guia Completo',
    type: ContentType.ARTICLE,
    url: 'https://personalitygrowth.com/intj-relationships',
    description: 'Navegando intimidade emocional como INTJ.',
    durationMinutes: 10,
    xpReward: 5,
    mbtiTypes: ['INTJ'],
    categories: ['relationships', 'emotions', 'intimacy'],
    difficulty: Difficulty.INTERMEDIATE,
  },
  {
    contentId: 'article_enfp_focus',
    title: 'ENFPs e Foco: Dominando a Dispersão',
    type: ContentType.ARTICLE,
    url: 'https://thoughtcatalog.com/enfp-focus',
    description: 'Estratégias para ENFPs manterem foco sem perder criatividade.',
    durationMinutes: 8,
    xpReward: 5,
    mbtiTypes: ['ENFP', 'ENTP'],
    categories: ['focus', 'productivity', 'adhd'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'article_istj_change',
    title: 'ISTJs Abraçando Mudanças',
    type: ContentType.ARTICLE,
    url: 'https://truity.com/istj-change',
    description: 'Como ISTJs podem se adaptar a mudanças mantendo estabilidade.',
    durationMinutes: 9,
    xpReward: 5,
    mbtiTypes: ['ISTJ', 'ISFJ'],
    categories: ['change', 'adaptability', 'growth'],
    difficulty: Difficulty.INTERMEDIATE,
  },
  {
    contentId: 'video_infp_boundaries',
    title: 'INFPs: Estabelecendo Limites Saudáveis',
    type: ContentType.VIDEO,
    url: 'https://youtube.com/watch?v=infp-boundaries',
    description: 'Como INFPs podem dizer não sem culpa.',
    durationMinutes: 12,
    xpReward: 10,
    mbtiTypes: ['INFP', 'ISFP'],
    categories: ['boundaries', 'assertiveness', 'self-care'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'video_estp_planning',
    title: 'ESTPs: Planejamento sem Rigidez',
    type: ContentType.VIDEO,
    url: 'https://youtube.com/watch?v=estp-planning',
    description: 'Sistemas de planejamento flexíveis para ESTPs.',
    durationMinutes: 14,
    xpReward: 10,
    mbtiTypes: ['ESTP', 'ESFP'],
    categories: ['planning', 'flexibility', 'organization'],
    difficulty: Difficulty.BEGINNER,
  },

  // ========================================
  // CONTEÚDO UNIVERSAL (todos os tipos)
  // ========================================
  {
    contentId: 'article_mindfulness_basics',
    title: 'Mindfulness: O Básico',
    type: ContentType.ARTICLE,
    url: 'https://mindful.org/meditation-101',
    description: 'Introdução à prática de mindfulness para todos os tipos.',
    durationMinutes: 6,
    xpReward: 5,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESFJ', 'ENFJ', 'ISFJ', 'INFJ', 'ESTP', 'ENTP', 'ISTP', 'INTP', 'ESFP', 'ENFP', 'ISFP', 'INFP'],
    categories: ['mindfulness', 'meditation', 'presence'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'video_growth_mindset',
    title: 'Mentalidade de Crescimento vs Fixa',
    type: ContentType.VIDEO,
    url: 'https://youtube.com/watch?v=growth-mindset',
    description: 'Carol Dweck explica como sua mentalidade molda sua realidade.',
    durationMinutes: 16,
    xpReward: 10,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESFJ', 'ENFJ', 'ISFJ', 'INFJ', 'ESTP', 'ENTP', 'ISTP', 'INTP', 'ESFP', 'ENFP', 'ISFP', 'INFP'],
    categories: ['mindset', 'growth', 'psychology'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'book_man_search_meaning',
    title: 'Em Busca de Sentido - Viktor Frankl',
    type: ContentType.BOOK,
    url: 'https://www.amazon.com/Mans-Search-Meaning-Viktor-Frankl',
    description: 'Encontrando propósito mesmo nas circunstâncias mais difíceis.',
    durationMinutes: 240,
    xpReward: 25,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESFJ', 'ENFJ', 'ISFJ', 'INFJ', 'ESTP', 'ENTP', 'ISTP', 'INTP', 'ESFP', 'ENFP', 'ISFP', 'INFP'],
    categories: ['meaning', 'purpose', 'philosophy', 'resilience'],
    difficulty: Difficulty.INTERMEDIATE,
  },
  {
    contentId: 'exercise_gratitude_journal',
    title: 'Exercício: Diário de Gratidão',
    type: ContentType.EXERCISE,
    url: 'https://pathfinder.com/exercises/gratitude',
    description: 'Prática diária de 5 minutos para cultivar gratidão.',
    durationMinutes: 5,
    xpReward: 10,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESFJ', 'ENFJ', 'ISFJ', 'INFJ', 'ESTP', 'ENTP', 'ISTP', 'INTP', 'ESFP', 'ENFP', 'ISFP', 'INFP'],
    categories: ['gratitude', 'wellbeing', 'journaling'],
    difficulty: Difficulty.BEGINNER,
  },
  {
    contentId: 'podcast_how_to_be_awesome',
    title: 'How to Be Awesome at Your Job',
    type: ContentType.PODCAST,
    url: 'https://awesomeatyourjob.com',
    description: 'Dicas práticas para excelência profissional.',
    durationMinutes: 40,
    xpReward: 15,
    mbtiTypes: ['ESTJ', 'ENTJ', 'ISTJ', 'INTJ', 'ESFJ', 'ENFJ', 'ISFJ', 'INFJ', 'ESTP', 'ENTP', 'ISTP', 'INTP', 'ESFP', 'ENFP', 'ISFP', 'INFP'],
    categories: ['career', 'productivity', 'excellence'],
    difficulty: Difficulty.BEGINNER,
  },

  // ========================================
  // CONTEÚDO AVANÇADO
  // ========================================
  {
    contentId: 'book_psychological_types_jung',
    title: 'Tipos Psicológicos - Carl Jung',
    type: ContentType.BOOK,
    url: 'https://www.amazon.com/Psychological-Types-Carl-Jung',
    description: 'A obra fundamental de Jung sobre tipos de personalidade.',
    durationMinutes: 600,
    xpReward: 40,
    mbtiTypes: ['INTJ', 'INFJ', 'INTP', 'INFP', 'ENTJ', 'ENFJ', 'ENTP', 'ENFP'],
    categories: ['jung', 'depth-psychology', 'theory', 'mbti'],
    difficulty: Difficulty.ADVANCED,
  },
  {
    contentId: 'video_cognitive_functions_deep',
    title: 'Funções Cognitivas: Estudo Profundo',
    type: ContentType.VIDEO,
    url: 'https://youtube.com/watch?v=cognitive-functions-deep',
    description: 'Análise detalhada de todas as 8 funções cognitivas.',
    durationMinutes: 90,
    xpReward: 25,
    mbtiTypes: ['INTJ', 'INFJ', 'INTP', 'INFP', 'ENTJ', 'ENFJ', 'ENTP', 'ENFP'],
    categories: ['mbti', 'cognitive-functions', 'depth', 'jung'],
    difficulty: Difficulty.ADVANCED,
  },
  {
    contentId: 'article_type_development',
    title: 'Desenvolvimento de Tipo: Amadurecimento Psicológico',
    type: ContentType.ARTICLE,
    url: 'https://personalityjunkie.com/type-development',
    description: 'Como cada tipo amadurece e desenvolve funções inferiores.',
    durationMinutes: 15,
    xpReward: 10,
    mbtiTypes: ['INTJ', 'INFJ', 'INTP', 'INFP', 'ENTJ', 'ENFJ', 'ENTP', 'ENFP', 'ISTJ', 'ISFJ', 'ISTP', 'ISFP', 'ESTJ', 'ESFJ', 'ESTP', 'ESFP'],
    categories: ['development', 'maturity', 'functions', 'growth'],
    difficulty: Difficulty.ADVANCED,
  },
];
